# Generated by Django 3.0.5 on 2020-04-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=200)),
                ('course_name', models.CharField(max_length=200)),
                ('course_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourseForYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_code', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('course_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmange_app.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_code', models.CharField(max_length=200)),
                ('department_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=200)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmange_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Facutly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=200)),
                ('faculty_name', models.CharField(max_length=200)),
                ('department_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmange_app.Department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseRegistrationForYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=200)),
                ('course_for_year_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmange_app.CourseForYear')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmange_app.Department'),
        ),
    ]
