# Generated by Django 3.0.5 on 2020-04-16 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmange_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseforyear',
            old_name='faculty_code',
            new_name='faculty_id',
        ),
    ]
