# Generated by Django 3.0.5 on 2020-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmange_app', '0002_auto_20200416_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseforyear',
            name='year',
            field=models.DateField(),
        ),
    ]
