# Generated by Django 3.0.5 on 2020-04-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmange_app', '0003_auto_20200418_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistrationforyear',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
