# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursecode', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=300)),
                ('program', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='defaultformats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyvalue', models.CharField(max_length=100)),
                ('formatvalue', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departmentname', models.CharField(max_length=300)),
                ('hod', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyname', models.CharField(max_length=300)),
                ('isperm', models.BooleanField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.department')),
            ],
        ),
        migrations.CreateModel(
            name='reg_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('courseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.courses')),
                ('facultyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='reg_student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regcourseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.reg_course')),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffname', models.CharField(max_length=300)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.department')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollnumber', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=10)),
                ('specialization', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.department')),
            ],
        ),
        migrations.AddField(
            model_name='reg_student',
            name='studentid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.student'),
        ),
        migrations.AddField(
            model_name='courses',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmanager.department'),
        ),
    ]
