# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanager', '0003_delete_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='programappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programtype', models.CharField(max_length=100)),
                ('programcode', models.CharField(max_length=100)),
            ],
        ),
    ]
