# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanager', '0004_programappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='departmentcode',
            field=models.CharField(default='Y', max_length=100),
            preserve_default=False,
        ),
    ]
