# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmanager', '0005_department_departmentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='username',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='username',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='Y', max_length=100),
            preserve_default=False,
        ),
    ]
