# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmanager', '0006_auto_20161021_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
